import { Client, Databases, Storage, Users } from 'node-appwrite';
import { env } from './env';

// ─── Appwrite Client ──────────────────────────────────────────────────────────

const client = new Client()
  .setEndpoint(env.APPWRITE_ENDPOINT)
  .setProject(env.APPWRITE_PROJECT_ID)
  .setKey(env.APPWRITE_API_KEY);

// ─── Appwrite Services ────────────────────────────────────────────────────────

export const databases = new Databases(client);
export const storage = new Storage(client);
export const users = new Users(client);

// ─── Database ID ──────────────────────────────────────────────────────────────

export const DATABASE_ID = env.APPWRITE_DATABASE_ID;

// ─── Collection ID Constants ──────────────────────────────────────────────────
// These must match the collection IDs created in your Appwrite project.

export const COLLECTIONS = {
  /** Registered doctors and patients */
  USERS: 'users',

  /** Patient digital health cards */
  HEALTH_CARDS: 'health_cards',

  /** Scheduled appointments between patients and doctors */
  APPOINTMENTS: 'appointments',

  /** Post-visit clinical records (SOAP notes, diagnoses, etc.) */
  CLINICAL_RECORDS: 'clinical_records',

  /** Digital prescriptions generated by doctors */
  PRESCRIPTIONS: 'prescriptions',

  /** In-app chat messages between doctors and patients */
  CHAT_MESSAGES: 'chat_messages',

  /** Lab test results uploaded by doctors or lab technicians */
  LAB_RESULTS: 'lab_results',

  /** System and appointment notifications */
  NOTIFICATIONS: 'notifications',

  /** Medication entries linked to prescriptions */
  MEDICATIONS: 'medications',

  /** Clinic profiles and location information */
  CLINICS: 'clinics',

  /** Audit trail for sensitive data access events */
  AUDIT_LOGS: 'audit_logs',
} as const;

export type CollectionId = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];

export default client;
